# Form implementation generated from reading ui file 'guinote.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(984, 509)
        MainWindow.setStyleSheet("QPushButton{\n"
"border : 0px solid blue;\n"
"background-color: #4380D3;\n"
"border-radius: 12px;\n"
"padding : 5px;\n"
"color: #ffffff;\n"
"}\n"
"QPushButton::pressed{\n"
"background-color : #05316D;\n"
"}\n"
"\n"
"\n"
"QListView{border : 0px solid red;font:300 10pt \"Ubuntu\";}\n"
"QListView::item\n"
"{\n"
"\n"
"border : 0px solid blue;\n"
"background-color: #4380D3;\n"
"color: #FFFFFF;\n"
"border-radius: 12px;\n"
"padding : 5px;\n"
"}\n"
"\n"
"\n"
"QTableWidget{border: none}\n"
"QTableWidget::item{background-color:  #4380D3;  color:#ffffff;}")
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setMaximumSize(QtCore.QSize(200, 16777215))
        self.tableWidget.setStyleSheet("")
        self.tableWidget.setAlternatingRowColors(True)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setStretchLastSection(False)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.btnTaskAdd = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTaskAdd.sizePolicy().hasHeightForWidth())
        self.btnTaskAdd.setSizePolicy(sizePolicy)
        self.btnTaskAdd.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnTaskAdd.setObjectName("btnTaskAdd")
        self.verticalLayout_2.addWidget(self.btnTaskAdd)
        self.btnTaskDel = QtWidgets.QPushButton(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnTaskDel.sizePolicy().hasHeightForWidth())
        self.btnTaskDel.setSizePolicy(sizePolicy)
        self.btnTaskDel.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnTaskDel.setObjectName("btnTaskDel")
        self.verticalLayout_2.addWidget(self.btnTaskDel)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.lid = QtWidgets.QLabel(parent=self.centralwidget)
        self.lid.setEnabled(False)
        self.lid.setObjectName("lid")
        self.horizontalLayout.addWidget(self.lid)
        self.lsubject = QtWidgets.QLabel(parent=self.centralwidget)
        self.lsubject.setObjectName("lsubject")
        self.horizontalLayout.addWidget(self.lsubject)
        self.esubject = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.esubject.setObjectName("esubject")
        self.horizontalLayout.addWidget(self.esubject)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.lfromdate = QtWidgets.QLabel(parent=self.centralwidget)
        self.lfromdate.setObjectName("lfromdate")
        self.horizontalLayout_2.addWidget(self.lfromdate)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.econtent = QtWidgets.QTextEdit(parent=self.centralwidget)
        self.econtent.setObjectName("econtent")
        self.verticalLayout.addWidget(self.econtent)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.bntOk = QtWidgets.QPushButton(parent=self.centralwidget)
        self.bntOk.setObjectName("bntOk")
        self.horizontalLayout_4.addWidget(self.bntOk)
        self.btnCancel = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnCancel.setStyleSheet("QPushButton{\n"
"border : 0px solid blue;\n"
"background : #4380D3;\n"
"border-radius: 12px;\n"
"padding : 5px;\n"
"}\n"
"QPushButton::pressed{\n"
"background : #05316D;\n"
"}")
        self.btnCancel.setObjectName("btnCancel")
        self.horizontalLayout_4.addWidget(self.btnCancel)
        self.verticalLayout.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_3.addLayout(self.verticalLayout)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.ltag = QtWidgets.QListWidget(parent=self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Policy.Minimum, QtWidgets.QSizePolicy.Policy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.ltag.sizePolicy().hasHeightForWidth())
        self.ltag.setSizePolicy(sizePolicy)
        self.ltag.setMinimumSize(QtCore.QSize(200, 0))
        self.ltag.setMaximumSize(QtCore.QSize(100, 16777215))
        font = QtGui.QFont()
        font.setFamily("Ubuntu")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(38)
        self.ltag.setFont(font)
        self.ltag.setStyleSheet("")
        self.ltag.setObjectName("ltag")
        self.verticalLayout_3.addWidget(self.ltag)
        self.btnTagEdit = QtWidgets.QPushButton(parent=self.centralwidget)
        self.btnTagEdit.setMinimumSize(QtCore.QSize(200, 0))
        self.btnTagEdit.setObjectName("btnTagEdit")
        self.verticalLayout_3.addWidget(self.btnTagEdit)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 984, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(parent=MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btnTaskAdd.setText(_translate("MainWindow", "Добавить"))
        self.btnTaskDel.setText(_translate("MainWindow", "Удалить"))
        self.lid.setText(_translate("MainWindow", "id"))
        self.lsubject.setText(_translate("MainWindow", "Subj"))
        self.lfromdate.setText(_translate("MainWindow", ""))
        self.bntOk.setText(_translate("MainWindow", "Сохранить"))
        self.btnCancel.setText(_translate("MainWindow", "Отмена"))
        self.btnTagEdit.setText(_translate("MainWindow", "Изменить"))
